# This workflow will build and push a new container image to Amazon ECR
# The following information will need to be included in your Github secrets:
# - DOCKER_USERNAME: docker user name
# - DOCKER_PASSWORD: password or access token

on:
  push:
    branches:
      - master
      - dev
      - dataseed
    paths:
      - 'requirements.txt'
      - 'packages.R'
      - 'local_install.R'
      - 'Dockerfile'
      - 'R/pkgs/**'
      - '.Rprofile'
      - 'packrat/**'

name: Deploy to DockerHub

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Tags
      id: tags
      env:
        IMAGE_TAG_RUN: ${{ github.run_number }}
        IMAGE_TAG_REF: ${{ github.ref }}
      run: |
        echo "::set-output name=shashort::$(git log -1 --pretty=%h)"
        echo "::set-output name=reftag::${IMAGE_TAG_REF##*/}-r$IMAGE_TAG_RUN"

    - name: Build Push Master
      uses: docker/build-push-action@v1
      if: contains( github.ref, 'master') || contains( github.base_ref, 'master' )
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: hopkinsidd/covidscenariopipeline
        tags: latest,latest-master,${{steps.tags.outputs.shashort}},${{steps.tags.outputs.reftag}},${{ github.sha }}

    - name: Build Push Dev
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: hopkinsidd/covidscenariopipeline
        tags: latest-dev,${{steps.tags.outputs.shashort}},${{steps.tags.outputs.reftag}},${{ github.sha }}
      if: contains( github.ref , 'dev') || contains( github.base_ref, 'dev' )


    - name: Build Push Dataseed
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: hopkinsidd/covidscenariopipeline
        tags: latest-dataseed,${{steps.tags.outputs.shashort}},${{steps.tags.outputs.reftag}},${{ github.sha }}
      if: contains( github.ref , 'dataseed') || contains( github.base_ref, 'dataseed' )
